import { Inter } from 'next/font/google'
import './globals.scss'
import Menu from '@/components/menu'
import Footer from '@/components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={inter.className}> <Menu/> {children} <Footer/></body>
    </html>
  )
}
